meta:
  engine: 4.1.0
  name: mangokb
  version: 0.0
  ref: &kb_ref "mangokb v0.0"
  author: ceoloide
  url: &kb_url https://github.com/monlovesmango/mangokb

units:
  # Key and keycap measures
  kx: cx # spacing between key centers (X-axis)
  ky: cy # spacing between key centers (Y-axis)
  ks: 18.5 # horizontal space between columns (default: 19)
  kp: 17.5 # vertical padding between keys (deafult: 19)
  kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
  kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
  kcw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  kch: 16.5 # keycap height (cherry: 18, choc: 16.5)
  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: 4.7 # Led Y position relative to the switch center
  led_pos_y_mcu: 4.2 # Led Y position relative to the switch center
  led_rotation: 0 # Led rotation
  # vertical_underglow_shift: -kp + 7.8  # How much to shift underglow leds tied to keys
  vertical_diode_shift: 1.5 # How much to shift to avoid overlap
  horizontal_diode_shift: -0.5 kcow - 0.85
  diode_rotation: -180 # Diode rotation
  switch_rotation: 180 # Hotswap south, led north

  hand_rotation: 0

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  # Case variables
  case_wall_thickness: 1.2
  pcb_to_case_wall_tolerance: 0.25
  bottom_plate_thickness: 1.0
  top_plate_thickness: 1.6
  internal_distance_between_plates: 4

points:
  zones:
    # main keys
    matrix:
      key:
        padding: kp
        spread: ks
        tags:
          - key
          - key_1u
          - matrix_key
      columns:
        outer:
          key.column_net: C5
          rows:
            number.key:
              led_prev: LED
              led_next: LED_1
            top.key:
              led_prev: LED_1
              led_next: LED_2
            home.key:
              led_prev: LED_2
              led_next: LED_3
            bottom.key:
              led_prev: LED_3
              led_next: LED_4
        pinky:
          key.stagger: .2ks
          key.column_net: C4
          rows:
            number.key:
              led_prev: LED_7
              led_next: LED_8
            top.key:
              led_prev: LED_6
              led_next: LED_7
            home.key:
              led_prev: LED_5
              led_next: LED_6
            bottom.key:
              led_prev: LED_4
              led_next: LED_5
        ring:
          key.stagger: .6ks
          key.column_net: C3
          rows:
            number.key:
              led_prev: LED_8
              led_next: LED_9
            top.key:
              led_prev: LED_9
              led_next: LED_10
            home.key:
              led_prev: LED_10
              led_next: LED_11
            bottom.key:
              led_prev: LED_11
              led_next: LED_12
        middle:
          key.stagger: .5ks
          key.column_net: C2
          rows:
            number.key:
              led_prev: LED_18
              led_next: LED_19
            top.key:
              led_prev: LED_17
              led_next: LED_18
            home.key:
              led_prev: LED_16
              led_next: LED_17
            bottom.key:
              led_prev: LED_15
              led_next: LED_16
        index:
          key.stagger: -.5ks
          key.column_net: C1
          rows:
            number.key:
              led_prev: LED_19
              led_next: LED_20
            top.key:
              led_prev: LED_20
              led_next: LED_21
            home.key:
              led_prev: LED_21
              led_next: LED_22
            bottom.key:
              led_prev: LED_22
              led_next: LED_23
        inner:
          key.column_net: C0
          rows:
            number.key:
              led_prev: LED_28
              led_next: LED_29
            top.key:
              led_prev: LED_27
              led_next: LED_28
            home.key:
              led_prev: LED_26
              led_next: LED_27
            bottom.key:
              led_prev: LED_25
              led_next: LED_26
      rows:
        bottom:
          row_net: R1
        home:
          row_net: R2
        top:
          row_net: R3
        number:
          row_net: R4
    # thumb cluster
    thumbmatrix:
      key:
        padding: kp
        spread: ks
        tags:
          - key
          - key_1u
          - thumb_key
      anchor:
        ref: matrix_ring_bottom
        shift: [0,-1.5kp]
      columns:
        ring:
          rows.bottom.skip: true
          key.column_net: C4
          rows.top.key.led_prev: LED_12
          rows.top.key.led_next: LED_13
        middle:
          rows.top.key.column_net: C2
          rows.top.key.led_prev: LED_14
          rows.top.key.led_next: LED_15
          rows.bottom.key.column_net: C3
          rows.bottom.key.led_prev: LED_13
          rows.bottom.key.led_next: LED_14
        index:
          rows.bottom.skip: true
          key.column_net: C1
          rows.top.key.led_prev: LED_23
          rows.top.key.led_next: LED_24
        inner:
          rows.bottom.skip: true
          key.stagger: .25kp
          key.column_net: C0
          key.tags:
              - key
              - thumb_key
              - key_1_5u
          rows.top.key.led_prev: LED_24
          rows.top.key.led_next: LED_25
      rows:
        top:
          row_net: R0
        bottom:
          row_net: R0
    # pinky cluster
    pinkymatrix:
      key:
        padding: kp
        spread: ks
      anchor:
        ref: matrix_outer_number
        shift: [0, 1.4kp]
      columns:
        outer:
          key.tags:
            - key
            - key_1u
            - pinky_key
            - rotary
          key.column_net: C5
          rows.row.key.led_prev: LED_29
          rows.row.key.led_next: LED_30
        pinky:
          key.column_net: C4
          key.tags:
            - key
            - key_1u
            - pinky_key
          rows.row.key.led_prev: LED_30
          rows.row.key.led_next: LED_31
      rows:
        row:
          row_net: R5
    # helper points
  rotate: hand_rotation
  mirror:
    ref: matrix_inner_number
    distance: 2ks
outlines:
  raw:
    - what: rectangle
      where: true
      size: [ks, kp]
  regular_keys:
    - what: rectangle
      where: [key_1u]
      size: [kcw,kch]
  one_and_half_keys:
    - what: rectangle
      where: [key_1_5u]
      size: [kcw, 1.5kch]
  keys:
    - name: regular_keys
    - operation: add
      name: one_and_half_keys
  board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumbmatrix_inner_top
          shift: [.5ks, -.75kp]
        - ref: thumbmatrix_ring_top
          shift: [-.5ks, -.5kp]
        - ref: matrix_outer_bottom
          shift: [-.5ks, -.5kp]
        - ref: pinkymatrix_outer_row
          shift: [-.5ks, .5kp]
        - ref: matrix_middle_number
          shift: [.5ks, .5kp]
        - ref: matrix_inner_number
          shift: [.5ks, .5kp]
      fillet: 3
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbmatrix_inner_top
          shift: [.5ks, -.75kp]
        - ref: mirror_thumbmatrix_ring_top
          shift: [-.5ks, -.5kp]
        - ref: mirror_matrix_outer_bottom
          shift: [-.5ks, -.5kp]
        - ref: mirror_pinkymatrix_outer_row
          shift: [-.5ks, .5kp]
        - ref: mirror_matrix_middle_number
          shift: [.5ks, .5kp]
        - ref: mirror_matrix_inner_number
          shift: [.5ks, .5kp]
      fillet: 3
  boards:
    - name: board_left
    - operation: add
      name: board_right
  promicro:
    - what: rectangle
      where: /pinkycluster_pinky/
      size: [33,17]
      adjust: 
        shift: [-9, 0]
  combo:
    - name: boards
    - operation: subtract
      name: keys
    - operation: stack
      name: promicro
pcbs:
  footprints:
    choc_hotswap:
      type: choc
      nets:
        from: =column_net
        to: GND
      params:
        keycaps: true
        reverse: true
        hotswap: true
    choc:
      type: choc
      anchor:
        rotate: 180
      nets:
        from: =column_net
        to: GND
      params:
        keycaps: true
        reverse: true
    trrs:
      type: trrs
    rotary:
      type: rotary
    promicro:
      type: promicro
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"