meta:
  engine: 4.1.0
  name: mangokb
  version: 0.0
  ref: &kb_ref "mangokb v0.0"
  author: monlovesmango
  url: &kb_url https://github.com/monlovesmango/mangokb


units:
  # Key and keycap measures
  kx: cx # spacing between key centers (X-axis)
  ky: cy # spacing between key centers (Y-axis)
  ks: 18.5 # horizontal space between columns (default: 19)
  kp: 17.5 # vertical padding between keys (deafult: 19)
  kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
  kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
  kcw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  kch: 16.5 # keycap height (cherry: 18, choc: 16.5)
  pcb_p: 1.4 # pcb padding
  pinky_stagger: .2kp
  ring_stagger: .6kp
  middle_stagger: .5kp
  index_stagger: -.5kp
  thumbmatrix_y_shift: -2.5kp
  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: 4.7 # Led Y position relative to the switch center
  led_pos_y_mcu: 3.4 # Led Y position relative to the switch center under mcu
  led_rotation: 0 # Led rotation
  # vertical_underglow_shift: -kp + 7.8  # How much to shift underglow leds tied to keys
  diode_y_shift: 0
  diode_x_shift: -0.5 kcow - 0.85
  diode_y_shift_mcu: -2
  diode_x_shift_mcu: -0.25 kcow 
  diode_y_shift_trrs: -4
  diode_x_shift_trrs: -ks + 0.5 kcow + 0.85
  diode_rotation: -180 # Diode rotation
  switch_rotation: 180 # Hotswap south, led north
  mcu_pos_x: .47ks - pcb_p
  mcu_pos_y: -1.3
  trrs_pos_x: -7
  trrs_pos_y: 12.8 + pcb_p
  trrs_rotation: -13.5

  hand_rotation: 0

  # mounting measures
  magnet_hole_diam: 3
  pcb_hold_diam: 5.4
  top_holes_y_shift: .5kp + .5middle_stagger
  bottom_holes_y_shift: -.75kp
  hole5_y_shift: ring_stagger + thumbmatrix_y_shift + kp
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  # Case variables
  case_wall_thickness: 1.2
  pcb_to_case_wall_tolerance: 0.25
  bottom_plate_thickness: 1.0
  top_plate_thickness: 1.6
  internal_distance_between_plates: 4

points:
  zones:
    # main keys
    matrix:
      key:
        padding: kp
        spread: ks
        tags:
          - key
          - key_1u
          - matrix_key
      columns:
        outer:
          key.column_net: C5
          rows:
            number.key:
              led_prev: LED_25
              led_next: LED_26
            top.key:
              led_prev: LED_26
              led_next: LED_27
            home.key:
              led_prev: LED_27
              led_next: LED_28
            bottom.key:
              led_prev: LED_28
              led_next: LED_29
        pinky:
          key.stagger: pinky_stagger
          key.column_net: C4
          rows:
            number.key:
              led_prev: LED_21
              led_next: LED_22
            top.key:
              led_prev: LED_22
              led_next: LED_23
            home.key:
              led_prev: LED_23
              led_next: LED_24
            bottom.key:
              led_prev: LED_24
              led_next: LED_25
        ring:
          key.stagger: ring_stagger
          key.column_net: C3
          rows:
            number.key:
              led_prev: LED_16
              led_next: LED_17
            top.key:
              led_prev: LED_17
              led_next: LED_18
            home.key:
              led_prev: LED_18
              led_next: LED_19
            bottom.key:
              led_prev: LED_19
              led_next: LED_20
        middle:
          key.stagger: middle_stagger
          key.column_net: C2
          rows:
            number.key:
              led_prev: LED_10
              led_next: LED_11
            top.key:
              led_prev: LED_11
              led_next: LED_12
            home.key:
              led_prev: LED_12
              led_next: LED_13
            bottom.key:
              led_prev: LED_13
              led_next: LED_14
        index:
          key.stagger: index_stagger
          key.column_net: C1
          rows:
            number.key:
              led_prev: LED_5
              led_next: LED_6
            top.key:
              led_prev: LED_6
              led_next: LED_7
            home.key:
              led_prev: LED_7
              led_next: LED_8
            bottom.key:
              led_prev: LED_8
              led_next: LED_9
        inner:
          key.column_net: C0
          rows:
            number.key:
              led_prev: LED
              led_next: LED_1
            top.key:
              led_prev: LED_1
              led_next: LED_2
            home.key:
              led_prev: LED_2
              led_next: LED_3
            bottom.key:
              led_prev: LED_3
              led_next: LED_4
      rows:
        bottom:
          row_net: R1
        home:
          row_net: R2
        top:
          row_net: R3
        number:
          row_net: R4
    # thumb cluster
    thumbmatrix:
      key:
        padding: kp
        spread: ks
        tags:
          - key
          - key_1u
          - thumb_key
      anchor:
        ref: matrix_ring_bottom
        shift: [0, thumbmatrix_y_shift]
      columns:
        ring:
          rows.thumbR5.skip: true
          key.column_net: C3
          rows.thumbR0.key:
            led_prev: LED_20
            led_next: LED_21
        middle:
          key.column_net: C2
          key.stagger: 1kp
          rows:
            thumbR0.key:
              led_prev: LED_14
              led_next: LED_15
            thumbR5.key:
              led_prev: LED_15
              led_next: LED_16
        index:
          rows.thumbR5.skip: true
          key.column_net: C1
          key.stagger: -1kp
          rows.thumbR0.key:
            led_prev: LED_9
            led_next: LED_10
        inner:
          rows.thumbR5.skip: true
          key.adjust.shift: [0, .25kp]
          key.column_net: C0
          key.tags:
              - key
              - thumb_key
              - key_1_5u
          rows.thumbR0.key:
            led_prev: LED_4
            led_next: LED_5
      rows:
        thumbR5:
          row_net: R5
        thumbR0:
          row_net: R0
    # pinky cluster
    pinkymatrix:
      key:
        padding: kp
        spread: ks
      anchor:
        ref: matrix_middle_number
        shift: [-3ks, 0]
      columns:
        outer:
          key.column_net: C5
          key.tags:
            - key
            - key_1u
            - pinky_key
            - rotary
          rows.pinky1.key.led_prev: LED_30
          rows.pinky1.key.led_next: LED_31
        pinky:
          key.column_net: C4
          key.tags:
            - key
            - key_1u
            - pinky_key
          rows.pinky1.key.led_prev: LED_29
          rows.pinky1.key.led_next: LED_30
      rows:
        pinky1:
          row_net: R5
    # helper points
    hole_1:
      key.tags: 
        - magnet_hole
      anchor:
        ref: matrix_ring_number
        shift: [0, top_holes_y_shift]
    hole_2:
      key.tags: 
        - magnet_hole
      anchor:
        ref: matrix_index_number
        shift: [0, top_holes_y_shift - .5]
    hole_3:
      key.tags: 
        - magnet_hole
      anchor:
        ref: matrix_index_bottom
        shift: [0, bottom_holes_y_shift]
    hole_4:
      key.tags: 
        - magnet_hole
      anchor:
        ref: matrix_ring_bottom
        shift: [0, bottom_holes_y_shift]
    hole_5:
      key.tags: 
        - magnet_hole
      anchor:
        ref: matrix_pinky_bottom
        shift: [0, hole5_y_shift]
  rotate: hand_rotation
  mirror:
    ref: matrix_inner_number
    distance: 2ks

outlines:
  debug_points:
    - what: rectangle
      where: true
      size: [6,0.01]
    - what: rectangle
      where: true
      size: [0.01,4]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [3,0]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [0,2]
    - what: rectangle
      where: [key]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key_1_5u]
      size: [kx, 1.5ky]
      operation: stack
    - what: rectangle
      where: /key/
      size: [kcow, kcoh]
      operation: stack
    - what: circle
      where: [screw]
      radius: 2
      operation: stack
  keycap_outlines:
    - what: rectangle
      fillet: 2
      where: [key_1u]
      size: [kcw, kch]
    - what: rectangle
      fillet: 2
      where: [key_1_5u]
      size: [kcw, 1.5kch]
  key_switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
  pcb_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumbmatrix_inner_thumbR0
          shift: [.5ks+pcb_p, -.75kp-pcb_p]
        - ref: thumbmatrix_ring_thumbR0
          shift: [-.5ks-pcb_p, -.5kp-pcb_p]
        - ref: matrix_outer_bottom
          shift: [-.5ks-pcb_p, -.5kp-pcb_p]
        - ref: pinkymatrix_outer_pinky1
          shift: [-.5ks-pcb_p, .5kp+pcb_p]
        - ref: matrix_middle_number
          shift: [.5ks+pcb_p, .5kp+pcb_p]
        - ref: matrix_inner_number
          shift: [.5ks+pcb_p, .5kp+pcb_p]
  pcb_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbmatrix_inner_thumbR0
          shift: [.5ks+pcb_p, -.75kp-pcb_p]
        - ref: mirror_thumbmatrix_ring_thumbR0
          shift: [-.5ks-pcb_p, -.5kp-pcb_p]
        - ref: mirror_matrix_outer_bottom
          shift: [-.5ks-pcb_p, -.5kp-pcb_p]
        - ref: mirror_pinkymatrix_outer_pinky1
          shift: [-.5ks-pcb_p, .5kp+pcb_p]
        - ref: mirror_matrix_middle_number
          shift: [.5ks+pcb_p, .5kp+pcb_p]
        - ref: mirror_matrix_inner_number
          shift: [.5ks+pcb_p, .5kp+pcb_p]
  pcb:
    - name: pcb_left
    - operation: add
      name: pcb_right
  combo:
    - name: pcb
    - operation: subtract
      name: keycap_outlines

pcbs:
  left:
    template: kicad8
    outlines:
      main:
        outline: pcb_left
    footprints:
      choc_hotswap:
        what: choc
        where: [[-/mirror/, -/pinkymatrix_outer/, "key"]]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          keycaps: true
          hotswap: true
        adjust:
          rotate: switch_rotation
      choc_outline:
        what: monlovesmango/choc_outline
        where: [[-/mirror/, /pinkymatrix_outer/]]
        params:
          keycaps: true
      diode:
        what: monlovesmango/diode
        where: [[-/mirror/, -/matrix_inner_number/, -/pinkymatrix_outer/, "key"]]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [diode_x_shift, diode_y_shift]
          rotate: 90 + diode_rotation
      diode_by_mcu:
        what: monlovesmango/diode
        where: [[-/mirror/, /pinkymatrix_outer/]]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [diode_x_shift_mcu, diode_y_shift_mcu]
          rotate: 90 + diode_rotation
      diode_by_trrs:
        what: monlovesmango/diode
        where: [[-/mirror/, /matrix_inner_number/]]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [diode_x_shift_trrs, diode_y_shift_trrs]
          rotate: 90 + diode_rotation
      led:
        what: ceoloide/led_sk6812mini-e
        where: [[-/mirror/, -/pinkymatrix/, "key"]]
        params:
          P1: VCC
          P2: "{{key.led_next}}"
          P3: GND
          P4: "{{key.led_prev}}"
          include_traces_vias: false
          signal_trace_width: signal_trace_width
          gnd_trace_width: gnd_trace_width
          vcc_trace_width: pwr_trace_width
        adjust:
          shift: [led_pos_x, led_pos_y]
          rotate: led_rotation
      led_under_mcu:
        what: ceoloide/led_sk6812mini-e
        where: [[-/mirror/, /pinkymatrix/, -/pinkymatrix_outer/, "key"]]
        params:
          P1: VCC
          P2: "{{key.led_next}}"
          P3: GND
          P4: "{{key.led_prev}}"
          include_traces_vias: false
          signal_trace_width: signal_trace_width
          gnd_trace_width: gnd_trace_width
          vcc_trace_width: pwr_trace_width
        adjust:
          shift: [led_pos_x, led_pos_y_mcu]
          rotate: led_rotation
      promicro:
        what: promicro
        # what: ceoloide/mcu_nice_nano
        where: pinkymatrix_outer_pinky1
        params:
          # RAW: {type: 'net', value: 'RAW'},
          # GND: {type: 'net', value: 'GND'},
          # RST: {type: 'net', value: 'RST'},
          # VCC: {type: 'net', value: 'VCC'},
          P21: LED
          # P20: {type: 'net', value: 'P20'},
          P19: R5
          P18: R4
          P15: R3
          P14: R2
          P16: R1
          P10: R0
          P1: DAT_A
          P0: DAT_C
          P2: RE_A
          P3: RE_C
          P4: C5
          P5: C4
          P6: C3
          P7: C2
          P8: C1
          P9: C0
          orientation: up
          # include_traces: true
          # show_silk_labels: true
          # show_via_labels: true
          # show_instructions: false
          # use_rectangular_jumpers: true
        adjust:
          shift: [mcu_pos_x, mcu_pos_y]
      trrs:
        what: ceoloide/trrs_pj320a
        # what: trrs
        where: matrix_inner_number
        params:
          R1: DAT_A
          SL: GND
          R2: DAT_C
          TP: VCC
          side: B
          # A: VCC
          # B: VCC
          # C: DAT
          # D: GND 
          # reverse: true
          # symmetric: true
        adjust:
          shift: [trrs_pos_x, trrs_pos_y]
          rotate: trrs_rotation
      rotary:
        what: monlovesmango/rotary_encoder_ec11_mini
        # what: rotary
        where: [[-/mirror/, "rotary"]]
        params:
          S1: "{{column_net}}"
          S2: "{{colrow}}"
        # params: 
        #   from: "{{column_net}}"
        #   to: "{{colrow}}"
          A: RE_A
          B: GND
          C: RE_C
        adjust:
          rotate: 90
      magnet_hole:
        what: monlovesmango/pcb_hole
        where: [[-/mirror/, "magnet_hole"]]
        params:
          diam: 5.4
      stablizer_hole:
        what: monlovesmango/pcb_hole
        where: [[-/mirror/, /number/, -/inner/],[-/mirror/, /top/, -/inner/],[-/mirror/, /home/, -/inner/],[-/mirror/, /middle_bottom/]]
        params:
          diam: 1.6
        adjust:
          shift: [.5ks - 1.1, -.5kp + 1.1]
      extra_stablizer_hole:
        what: monlovesmango/pcb_hole
        where: [[-/mirror/, /outer_number/]]
        params:
          diam: 1.6
        adjust:
          shift: [.5ks, .5kp + .5pinky_stagger]
